[package]
name = "day02b"
version = "0.1.0"
authors = ["Maximilian Konter <maximilian.konter@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.6.0"
lazy_static = "1.4.0"
